# Generated by Django 3.2.20 on 2023-09-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230913_0608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='topic',
            new_name='user',
        ),
    ]
