# Generated by Django 3.2.20 on 2023-09-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_topic_room_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='topic',
        ),
    ]
